service: authentication

frameworkVersion: '3'
variablesResolutionMode: 20210326

plugins:
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-domain-manager

params:
  default:
    apiUserPoolClient: ${ssm:/nevvi/cognito/nevvi-development-api-users/clients/authentication/id}
    apiUserPoolClientSecret: ${ssm:/nevvi/cognito/nevvi-development-api-users/clients/authentication/secret}
    apiUserPoolName: nevvi-development-api-users
    basePath: ${self:provider.stage}-authentication
    domainName: api.development.nevvi.net
    oauthDomain: https://nevvi-development-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
    publicUserPoolName: nevvi-development-public-users
  development:
    basePath: authentication
  production:
    apiUserPoolClient: ${ssm:/nevvi/cognito/nevvi-api-users/clients/authentication/id}
    apiUserPoolClientSecret: ${ssm:/nevvi/cognito/nevvi-api-users/clients/authentication/secret}
    apiUserPoolName: nevvi-api-users
    basePath: authentication
    domainName: api.nevvi.net
    oauthDomain: https://nevvi-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
    publicUserPoolName: nevvi-public-users

custom:
  prune:
    automatic: true
    number: 2
  customDomain:
    domainName: ${param:domainName}
    basePath: ${param:basePath}
  publicUserPoolName: ${param:publicUserPoolName}
  publicUserPoolArn: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/arn}
  publicUserPoolId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/id}
  publicUserPoolClientId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/clients/authentication/id}
  apiUserPoolName: ${param:apiUserPoolName}
  apiUserPoolArn: ${ssm:/nevvi/cognito/${self:custom.apiUserPoolName}/arn}

provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: authentication-${self:provider.stage}
  stackName: authentication-${self:provider.stage}
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}
  environment:
    OAUTH_DOMAIN_URL: ${param:oauthDomain}
    PUBLIC_USER_POOL_CLIENT_ID: ${self:custom.publicUserPoolClientId}
    PUBLIC_USER_POOL_ID: ${self:custom.publicUserPoolId}
    USER_API_URL: https://${param:domainName}/user
    API_CLIENT_ID: ${param:apiUserPoolClient}
    API_CLIENT_SECRET: ${param:apiUserPoolClientSecret}
    USER_API_SCOPES: user_api/user_api.all

functions:
  authorizer:
    handler: src/functions/Authorizer.authorize

  register:
    handler: src/functions/AuthHandler.register
    events:
      - http:
          path: /v1/register
          method: post

  confirm:
    handler: src/functions/AuthHandler.confirm
    events:
      - http:
          path: /v1/confirm
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  login:
    handler: src/functions/AuthHandler.login
    events:
      - http:
          path: /v1/login
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  logout:
    handler: src/functions/AuthHandler.logout
    events:
      - http:
          path: /v1/logout
          method: post

  sendVerificationCode:
    handler: src/functions/AuthHandler.sendCode
    events:
      - http:
          path: /v1/users/{userId}/sendCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:GetUserAttributeVerificationCode
        Resource: ${self:custom.publicUserPoolArn}

  confirmVerificationCode:
    handler: src/functions/AuthHandler.confirmCode
    events:
      - http:
          path: /v1/users/{userId}/confirmCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:VerifyUserAttribute
          - cognito-idp:GetUser
        Resource: ${self:custom.publicUserPoolArn}

  updateUser:
    handler: src/functions/AuthHandler.updateUser
    events:
      - http:
          path: /api/v1/users/{userId}
          method: patch
          authorizer:
            arn: ${self:custom.apiUserPoolArn}
            scopes:
              - user_api/user_api.all
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:ListUsers
          - cognito-idp:AdminUpdateUserAttributes
        Resource: ${self:custom.publicUserPoolArn}