service: authentication

frameworkVersion: '3'
variablesResolutionMode: 20210326

plugins:
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-domain-manager
  - serverless-plugin-split-stacks

params:
  default:
    userApiKey: ${ssm:/nevvi/lambda/development/user-api-key}
    authenticationApiKey: ${ssm:/nevvi/lambda/development/authentication-api-key}
    basePath: ${self:provider.stage}-authentication
    domainName: api.development.nevvi.net
    oauthDomain: https://nevvi-development-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
    publicUserPoolName: nevvi-development-public-users
  development:
    basePath: authentication
  production:
    userApiKey: ${ssm:/nevvi/lambda/production/user-api-key}
    authenticationApiKey: ${ssm:/nevvi/lambda/production/authentication-api-key}
    basePath: authentication
    domainName: api.nevvi.net
    oauthDomain: https://nevvi-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
    publicUserPoolName: nevvi-public-users

custom:
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: false
  prune:
    automatic: true
    number: 2
  customDomain:
    domainName: ${param:domainName}
    basePath: ${param:basePath}
  publicUserPoolName: ${param:publicUserPoolName}
  publicUserPoolArn: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/arn}
  publicUserPoolId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/id}
  publicUserPoolClientId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/clients/authentication/id}

provider:
  name: aws
  runtime: nodejs16.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: authentication-${self:provider.stage}
  stackName: authentication-${self:provider.stage}
  apiGateway:
    apiKeys:
      - name: authentication-internal-api-key-${self:provider.stage}
        value: ${param:authenticationApiKey}
        description: API key for internal endpoints
    usagePlan:
      quota:
        limit: 10000
        period: MONTH
      throttle:
        rateLimit: 100
        burstLimit: 200
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}
  environment:
    OAUTH_DOMAIN_URL: ${param:oauthDomain}
    PUBLIC_USER_POOL_CLIENT_ID: ${self:custom.publicUserPoolClientId}
    PUBLIC_USER_POOL_ID: ${self:custom.publicUserPoolId}
    USER_API_URL: https://${param:domainName}/user
    MIN_IOS_VERSION: 1.9
    USER_API_KEY: ${param:userApiKey}

functions:
  authorizer:
    handler: src/functions/Authorizer.authorize

  minAppVersions:
    handler: src/functions/AuthHandler.getMinAppVersions
    events:
      - http:
          path: /v1/versions
          method: get

  register:
    handler: src/functions/AuthHandler.register
    events:
      - http:
          path: /v1/register
          method: post

  confirm:
    handler: src/functions/AuthHandler.confirm
    events:
      - http:
          path: /v1/confirm
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  login:
    handler: src/functions/AuthHandler.login
    events:
      - http:
          path: /v1/login
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  refreshLogin:
    handler: src/functions/AuthHandler.refreshLogin
    events:
      - http:
          path: /v1/refreshLogin
          method: post

  logout:
    handler: src/functions/AuthHandler.logout
    events:
      - http:
          path: /v1/logout
          method: post

  resendSignupCode:
    handler: src/functions/AuthHandler.resendSignupCode
    events:
      - http:
          path: /v1/resendSignupCode
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
          - cognito-idp:ResendConfirmationCode
        Resource: ${self:custom.publicUserPoolArn}

  forgotPassword:
    handler: src/functions/AuthHandler.forgotPassword
    events:
      - http:
          path: /v1/forgotPassword
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
          - cognito-idp:ForgotPassword
        Resource: ${self:custom.publicUserPoolArn}

  confirmForgotPassword:
    handler: src/functions/AuthHandler.confirmForgotPassword
    events:
      - http:
          path: /v1/confirmForgotPassword
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
          - cognito-idp:ConfirmForgotPassword
        Resource: ${self:custom.publicUserPoolArn}

  sendVerificationCode:
    handler: src/functions/AuthHandler.sendCode
    events:
      - http:
          path: /v1/users/{userId}/sendCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:GetUserAttributeVerificationCode
        Resource: ${self:custom.publicUserPoolArn}

  confirmVerificationCode:
    handler: src/functions/AuthHandler.confirmCode
    events:
      - http:
          path: /v1/users/{userId}/confirmCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:VerifyUserAttribute
          - cognito-idp:GetUser
        Resource: ${self:custom.publicUserPoolArn}

  updateUser:
    handler: src/functions/AuthHandler.updateUser
    events:
      - http:
          path: /api/v1/users/{userId}
          method: patch
          private: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:ListUsers
          - cognito-idp:AdminUpdateUserAttributes
        Resource: ${self:custom.publicUserPoolArn}