service: authentication

frameworkVersion: '2'
variablesResolutionMode: 20210326

plugins:
  - serverless-prune-plugin
  - serverless-iam-roles-per-function
  - serverless-webpack
  - serverless-domain-manager

custom:
  prune:
    automatic: true
    number: 2
  oauthDomainMap:
    default: https://nevvi-development-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
    production: https://nevvi-api-users.auth.us-east-1.amazoncognito.com/oauth2/token
  domainNameMap:
    default: api.development.nevvi.net
    production: api.nevvi.net
  basePathMap:
    production: authentication
    development: authentication
    default: ${self:provider.stage}-authentication
  customDomain:
    domainName: ${self:custom.domainNameMap.${self:provider.stage}, self:custom.domainNameMap.default}
    basePath: ${self:custom.basePathMap.${self:provider.stage}, self:custom.basePathMap.default}
  apiUserPoolNameMap:
    default: nevvi-development-api-users
    production: nevvi-api-users
  publicUserPoolNameMap:
    default: nevvi-development-public-users
    production: nevvi-public-users
  apiUserPoolClientMap:
    default: ${ssm:/nevvi/cognito/nevvi-development-api-users/clients/authentication/id}
    production: ${ssm:/nevvi/cognito/nevvi-api-users/clients/authentication/id}
  apiUserPoolClientSecretMap:
    default: ${ssm:/nevvi/cognito/nevvi-development-api-users/clients/authentication/secret}
    production: ${ssm:/nevvi/cognito/nevvi-api-users/clients/authentication/secret}
  publicUserPoolName: ${self:custom.publicUserPoolNameMap.${self:provider.stage}, self:custom.publicUserPoolNameMap.default}
  publicUserPoolArn: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/arn}
  publicUserPoolId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/id}
  publicUserPoolClientId: ${ssm:/nevvi/cognito/${self:custom.publicUserPoolName}/clients/authentication/id}
  apiUserPoolName: ${self:custom.apiUserPoolNameMap.${self:provider.stage}, self:custom.apiUserPoolNameMap.default}
  apiUserPoolArn: ${ssm:/nevvi/cognito/${self:custom.apiUserPoolName}/arn}


provider:
  name: aws
  runtime: nodejs14.x
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: authentication-${self:provider.stage}
  stackName: authentication-${self:provider.stage}
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}
  environment:
    OAUTH_DOMAIN_URL: ${self:custom.oauthDomainMap.${self:provider.stage}, self:custom.oauthDomainMap.default}
    PUBLIC_USER_POOL_CLIENT_ID: ${self:custom.publicUserPoolClientId}
    PUBLIC_USER_POOL_ID: ${self:custom.publicUserPoolId}
    USER_API_URL: https://${self:custom.domainNameMap.${self:provider.stage}, self:custom.domainNameMap.default}/user
    API_CLIENT_ID: ${self:custom.apiUserPoolClientMap.${self:provider.stage}, self:custom.apiUserPoolClientMap.default}
    API_CLIENT_SECRET: ${self:custom.apiUserPoolClientSecretMap.${self:provider.stage}, self:custom.apiUserPoolClientSecretMap.default}
    USER_API_SCOPES: user_api/user_api.all

functions:
  authorizer:
    handler: src/functions/Authorizer.authorize

  register:
    handler: src/functions/AuthHandler.register
    events:
      - http:
          path: /v1/register
          method: post

  confirm:
    handler: src/functions/AuthHandler.confirm
    events:
      - http:
          path: /v1/confirm
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  login:
    handler: src/functions/AuthHandler.login
    events:
      - http:
          path: /v1/login
          method: post
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}

  logout:
    handler: src/functions/AuthHandler.logout
    events:
      - http:
          path: /v1/logout
          method: post

  sendVerificationCode:
    handler: src/functions/AuthHandler.sendCode
    events:
      - http:
          path: /v1/users/{userId}/sendCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:GetUserAttributeVerificationCode
        Resource: ${self:custom.publicUserPoolArn}

  confirmVerificationCode:
    handler: src/functions/AuthHandler.confirmCode
    events:
      - http:
          path: /v1/users/{userId}/confirmCode
          method: post
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:VerifyUserAttribute
        Resource: ${self:custom.publicUserPoolArn}

  getUser:
    handler: src/functions/UserHandler.getUser
    events:
      - http:
          path: /v1/users/{userId}
          method: get
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminGetUser
        Resource: ${self:custom.publicUserPoolArn}

  updateUser:
    handler: src/functions/UserHandler.updateUser
    events:
      - http:
          path: /v1/users/{userId}
          method: patch
          authorizer:
            name: authorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:AdminGetUser
          - cognito-idp:ListUsers
          - cognito-idp:AdminUpdateUserAttributes
        Resource: ${self:custom.publicUserPoolArn}

  searchUser:
    handler: src/functions/UserHandler.searchUser
    events:
      - http:
          path: /api/v1/users
          method: get
          authorizer:
            arn: ${self:custom.apiUserPoolArn}
            scopes:
              - user_api/user_api.all
    iamRoleStatements:
      - Effect: Allow
        Action:
          - cognito-idp:ListUsers
        Resource: ${self:custom.publicUserPoolArn}