org: nevvi
app: nevvi
service: user

frameworkVersion: '4'

plugins:
  - serverless-domain-manager
  - serverless-iam-roles-per-function
  - serverless-plugin-split-stacks
  - serverless-prune-plugin
  - serverless-python-requirements

package:
  patterns:
    - '!./**'           # exclude everything first
    - './src/**'        # include your source directory
    - '../../shared/**' # include shared modules

custom:
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: false
  prune:
    automatic: true
    number: 2
  customDomain:
    domainName: ${param:domainName}
    basePath: ${param:basePath}
  pythonRequirements:
    dockerizePip: true

params:
  default:
    userApiKey: ${ssm:/nevvi/lambda/development/user-api-key}
    authenticationApiKey: ${ssm:/nevvi/lambda/development/authentication-api-key}
    basePath: ${self:provider.stage}-user
    defaultProfileImage: https://nevvi-user-images-dev.s3.amazonaws.com/Default_Profile_Picture.png
    domainName: api.development.nevvi.net
    mongoUri: ${ssm:/nevvi/mongo/nevvi-development/uri}
    notificationQueueArn: ${ssm:/nevvi/sqs/notifications-dev/arn}
    notificationQueueUrl: ${ssm:/nevvi/sqs/notifications-dev/url}
    refreshSuggestionsQueueArn: ${ssm:/nevvi/sqs/refresh-suggestions-dev/arn}
    refreshSuggestionsQueueUrl: ${ssm:/nevvi/sqs/refresh-suggestions-dev/url}
    userImagesBucketArn: ${ssm:/nevvi/s3/nevvi-user-images-dev/arn}
    userImagesBucketName: nevvi-user-images-dev
  development:
    basePath: user
  production:
    userApiKey: ${ssm:/nevvi/lambda/production/user-api-key}
    authenticationApiKey: ${ssm:/nevvi/lambda/production/authentication-api-key}
    basePath: user
    defaultProfileImage: https://nevvi-user-images.s3.amazonaws.com/Default_Profile_Picture.png
    mongoUri: ${ssm:/nevvi/mongo/nevvi/uri}
    notificationQueueArn: ${ssm:/nevvi/sqs/notifications/arn}
    notificationQueueUrl: ${ssm:/nevvi/sqs/notifications/url}
    domainName: api.nevvi.net
    refreshSuggestionsQueueArn: ${ssm:/nevvi/sqs/refresh-suggestions/arn}
    refreshSuggestionsQueueUrl: ${ssm:/nevvi/sqs/refresh-suggestions/url}
    userImagesBucketArn: ${ssm:/nevvi/s3/nevvi-user-images/arn}
    userImagesBucketName: nevvi-user-images

provider:
  name: aws
  runtime: python3.12
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: user-${self:provider.stage}
  stackName: user-${self:provider.stage}
  apiGateway:
    binaryMediaTypes:
      - 'multipart/form-data'
      - 'image/png'
      - 'image/jpeg'
      - 'application/octet-stream'
    apiKeys:
      - name: user-internal-api-key-${self:provider.stage}
        value: ${param:userApiKey}
        description: API key for internal endpoints
    usagePlan:
      quota:
        limit: 10000
        period: MONTH
      throttle:
        rateLimit: 100
        burstLimit: 200
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}
  environment:
    MONGO_URI: ${param:mongoUri}
    DEFAULT_PROFILE_IMAGE: ${param:defaultProfileImage}
    IMAGE_BUCKET: ${param:userImagesBucketName}
    EMAIL_FROM_ARN: arn:aws:ses:us-east-1:275527036335:identity/nevvi.net
    NOTIFICATION_QUEUE_URL: ${param:notificationQueueUrl}
    REFRESH_SUGGESTIONS_QUEUE_URL: ${param:refreshSuggestionsQueueUrl}
    ADMIN_EMAIL: tyler.cobb@nevvi.net
    AUTHENTICATION_API_URL: https://${param:domainName}/authentication
    AUTHENTICATION_API_KEY: ${param:authenticationApiKey}

functions:
  userAuthorizer:
    handler: src/functions/user_authorizer.authorize

  # region user

  getUser:
    handler: src/functions/user_handler.get_user
    events:
      - http:
          path: /v1/users/{userId}
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  createUser:
    handler: src/functions/user_handler.create_user
    events:
      - http:
          path: /api/v1/users
          method: post
          private: true

  deleteUser:
    handler: src/functions/user_handler.delete_user
    events:
      - http:
          path: /v1/users/{userId}
          method: delete
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendRawEmail
        Resource: arn:aws:ses:us-east-1:275527036335:identity/nevvi.net

  updateUserContact:
    handler: src/functions/user_handler.update_user_contact
    events:
      - http:
          path: /api/v1/users/{userId}/contact
          method: post
          private: true

  updateUser:
    handler: src/functions/user_handler.update_user
    events:
      - http:
          path: /v1/users/{userId}
          method: patch
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  updateUserImage:
    handler: src/functions/user_handler.update_user_image
    events:
      - http:
          path: /v1/users/{userId}/image
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - s3:*
        Resource:
          - ${param:userImagesBucketArn}
          - ${param:userImagesBucketArn}/*

  searchUsers:
    handler: src/functions/user_handler.search_users
    events:
      - http:
          path: /v1/users/search
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  searchContacts:
    handler: src/functions/user_handler.search_potential_contacts
    events:
      - http:
          path: /v1/users/search/contacts
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  notifyUsers:
    handler: src/functions/user_handler.notify_out_of_sync_users
    events:
      - schedule:
          rate: cron(0 17 * * ? *) # noon est every day (17 UTC - 5 hours)
          enabled: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:notificationQueueArn}

  notifyBirthdays:
    handler: src/functions/user_handler.notify_birthdays
    events:
      - schedule:
          rate: cron(0 15 * * ? *) # 10am est every day (15 UTC - 5 hours)
          enabled: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:notificationQueueArn}

  getRejectedUsers:
    handler: src/functions/user_handler.get_rejected_users
    events:
      - http:
          path: /v1/users/{userId}/connections/rejected
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  # endregion

  # region invite

  inviteUser:
    handler: src/functions/invite_handler.invite_user
    events:
      - http:
          path: /v1/users/{userId}/invite
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sns:Publish
        Resource: '*'

  # endregion

  # region connection requests
  createConnectionRequest:
    handler: src/functions/connection_handler.request_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/requests
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:notificationQueueArn}
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:refreshSuggestionsQueueArn}

  confirmConnectionRequest:
    handler: src/functions/connection_handler.confirm_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/requests/confirm
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:notificationQueueArn}
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:refreshSuggestionsQueueArn}

  denyConnectionRequest:
    handler: src/functions/connection_handler.deny_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/requests/deny
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:refreshSuggestionsQueueArn}

  getPendingRequests:
    handler: src/functions/connection_handler.get_open_requests
    events:
      - http:
          path: /v1/users/{userId}/connections/requests/pending
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  # endregion

  # region suggestions

  refreshAllSuggestions:
    handler: src/functions/suggestion_handler.refresh_all_suggestions
    events:
      - schedule:
          rate: cron(0 11 * * ? *) # 6am est every day (11 UTC - 5 hours)
          enabled: true
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:refreshSuggestionsQueueArn}

  getSuggestions:
    handler: src/functions/suggestion_handler.get_suggested_connections
    events:
      - http:
          path: /v1/users/{userId}/suggestions
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  ignoreSuggestion:
    handler: src/functions/suggestion_handler.ignore_suggestion
    events:
      - http:
          path: /v1/users/{userId}/suggestions/{suggestionId}
          method: delete
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - sqs:SendMessage
        Resource: ${param:refreshSuggestionsQueueArn}

  refreshSuggestions:
    handler: src/functions/suggestion_handler.refresh_suggestions
    events:
      - sqs:
          arn: ${param:refreshSuggestionsQueueArn}

  # endregion

  # region connections

  getConnections:
    handler: src/functions/connection_handler.get_connections
    events:
      - http:
          path: /v1/users/{userId}/connections
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  getConnection:
    handler: src/functions/connection_handler.get_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/{connectedUserId}
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  updateConnection:
    handler: src/functions/connection_handler.update_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/{connectedUserId}
          method: patch
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  blockConnection:
    handler: src/functions/connection_handler.block_connection
    events:
      - http:
          path: /v1/users/{userId}/connections/{connectedUserId}
          method: delete
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  # endregion

  # region connection groups
  createConnectionGroup:
    handler: src/functions/connection_group_handler.create_group
    events:
      - http:
          path: /v1/users/{userId}/connection-groups
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  getConnectionGroups:
    handler: src/functions/connection_group_handler.get_groups
    events:
      - http:
          path: /v1/users/{userId}/connection-groups
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  deleteConnectionGroup:
    handler: src/functions/connection_group_handler.delete_group
    events:
      - http:
          path: /v1/users/{userId}/connection-groups/{groupId}
          method: delete
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  exportConnectionGroup:
    handler: src/functions/connection_group_handler.export_group
    events:
      - http:
          path: /v1/users/{userId}/connection-groups/{groupId}/export
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request
    iamRoleStatements:
      - Effect: Allow
        Action:
          - ses:SendRawEmail
        Resource: arn:aws:ses:us-east-1:275527036335:identity/*

  getConnectionsInGroup:
    handler: src/functions/connection_group_handler.get_connections
    events:
      - http:
          path: /v1/users/{userId}/connection-groups/{groupId}/connections
          method: get
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  addToConnectionGroup:
    handler: src/functions/connection_group_handler.add_connection
    events:
      - http:
          path: /v1/users/{userId}/connection-groups/{groupId}/connections
          method: post
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  removeFromConnectionGroup:
    handler: src/functions/connection_group_handler.remove_connection
    events:
      - http:
          path: /v1/users/{userId}/connection-groups/{groupId}/connections
          method: delete
          authorizer:
            name: userAuthorizer
            resultTtlInSeconds: 0
            type: request

  # endregion
