org: nevvi
app: nevvi
service: notification

frameworkVersion: '4'

plugins:
  - serverless-domain-manager
  - serverless-iam-roles-per-function
  - serverless-plugin-split-stacks
  - serverless-prune-plugin
  - serverless-python-requirements

package:
  patterns:
    - '!./**'           # exclude everything first
    - './src/**'        # include your source directory

custom:
  splitStacks:
    perFunction: false
    perType: true
    perGroupFunction: false
  prune:
    automatic: true
    number: 2
  customDomain:
    domainName: ${param:domainName}
    basePath: ${param:basePath}
  pythonRequirements:
    dockerizePip: true

params:
  default:
    basePath: ${self:provider.stage}-notification
    domainName: api.development.nevvi.net
    firebaseCredentials: ${ssm:/nevvi/firebase/credentials}
    mongoUri: ${ssm:/nevvi/mongo/nevvi-development/uri}
    notificationQueueArn: ${ssm:/nevvi/sqs/notifications-dev/arn}
  development:
    basePath: notification
  production:
    basePath: notification
    mongoUri: ${ssm:/nevvi/mongo/nevvi/uri}
    notificationQueueArn: ${ssm:/nevvi/sqs/notifications/arn}
    domainName: api.nevvi.net

provider:
  name: aws
  runtime: python3.12
  lambdaHashingVersion: 20201221
  stage: ${opt:stage, 'test'}
  region: ${opt:region, 'us-east-1'}
  apiName: notification-${self:provider.stage}
  stackName: notification-${self:provider.stage}
  deploymentBucket:
    name: nevvi-serverless-deployment-bucket
  deploymentPrefix: ${self:provider.stage}
  environment:
    FIREBASE_CREDENTIALS: ${param:firebaseCredentials}
    MONGO_URI: ${param:mongoUri}

functions:
  notificationAuthorizer:
    handler: src/functions/notification_authorizer.authorize

  updateDeviceToken:
    handler: src/functions/notification_handler.update_device_token
    events:
      - http:
          path: /v1/users/{userId}/notifications/token
          method: post
          authorizer:
            name: notificationAuthorizer
            resultTtlInSeconds: 0
            type: request

  sendNotification:
    handler: src/functions/notification_handler.send_notification
    events:
      - sqs:
          arn: ${param:notificationQueueArn}

